<?php
/**
 * @file
 * Code for the Groups Events feature.
 */

include_once 'groups_events.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function groups_events_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_menu_alter()
 */
function groups_events_menu_alter(&$items) {
  // show attendees tab for logged-in users only
  $items['node/%node/attendees']['access callback'] = 'user_is_logged_in';
}

/**
 * Implements hook_field_default_field_instances_alter()
 *
 * Override event address field teaser display to show
 * locality, country part of the address.
 */
function groups_events_field_default_field_instances_alter(&$fields) {
  if (isset($fields['node-event-field_address'])) {
    $field = &$fields['node-event-field_address'];
    $field['display']['teaser']['settings']['components'] = array(
      'administrative_area' => 'administrative_area',
      'locality' => 'locality',
      'country' => 'country',
    );
  }
}