<?php

/**
 * Implements hook_instal()
 *
 * Set initial leaflet mapbox variables.
 */
function groups_directory_install() {
  groups_directory_update_7301();
}

/**
 * Set leaflet_mapbox 1.4 variables
 *
 * The v4 mapbox api require mapbox_label, mapbox_code settings.
 */
function groups_directory_update_7301() {
  variable_set('leaflet_mapbox_label', 'leaflet-mapbox');
  variable_set('leaflet_mapbox_code', 'mapbox.light');
}