<?php
/**
 * @file
 * Code for the Groups User Profile feature.
 */

include_once 'groups_user_profile.features.inc';

/**
 * Implements hook_field_default_field_instances_alter()
 *
 * Add profile teaser settings to user profile's twitter url
 * field.
 */
function groups_user_profile_field_default_field_instances_alter(&$fields) {
  if (isset($fields['user-user-field_twitter_url'])) {
    $field = &$fields['user-user-field_twitter_url'];
    $field['display']['profile_teaser'] = array(
      'label' => 'hidden',
      'module' => 'groups_social_link',
      'settings' => array(
        'provider' => 'twitter',
      ),
      'type' => 'groups_social_link_formatter',
      'weight' => 2,
    );
  }
}

/**
 * Implements hook_form_user_profile_form_alter()
 *
 * Override ambassador-region field visibility.
 */
function groups_user_profile_form_user_profile_form_alter(&$form, &$form_state,
  $form_id) {
  $current_user = user_uid_optional_load();
  $roles = array('ambassador', 'community_manager', 'administrator');
  $check = array_intersect($roles, array_values($current_user->roles));
  if (empty($check)) {
    $form['field_ambassador_region']['#access'] = FALSE;
  }
}