<?php

function groups_common_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'search_block_form') {
    // remove content selector from search block
    $form['custom_search_types']['#type'] = 'hidden';
    $form['custom_search_types']['#default_value'] = 'o-search_facetapi';
  }
}

/**
 * Implements hook_leaflet_map_info_alter().
 * Disable scrollWheelZoom feature for all leaflet maps.
 *
 * @param unknown $map_info
 */

function groups_common_leaflet_map_info_alter(&$map_info) {
  foreach ($map_info as $map_id => $info) {
    $map_info[$map_id]['settings']['scrollWheelZoom'] = FALSE;
  }
}

/**
 * Implement hook_commons_utility_links_alter()
 *
 * Rename login link link to "Signup or Sign in"
 */

function groups_common_commons_utility_links_alter(&$links) {
  if (isset($links['login'])) {
    $links['login']['title'] = t('Sign up or Login');
  }
  if (isset($links['signup'])) {
    $links['signup']['title'] = t('Sign in');
  }
}
